In [1]:
import numpy as np 

2. Generate at random 3 matrices of size $3 \times 3$ and fill each entry with a random integer chosen from -10 to 10. Use an existing
package to compute the inverse of each matrix if it exists. Include in your report:
    - Each of the 3 matrices
    - The inverses computed with the package
    - Compute the product of each matrix with its inverse to check that you obtain the identity matrix.

In [2]:
# this way the numbers don't change everytime it re-runs
np.random.seed(42) 

In [3]:
# generating the 3 matrices
matrix_1 = np.random.randint(-10, 10, size=(3,3)) 
matrix_2 = np.random.randint(-10, 10, size=(3,3)) 
matrix_3 = np.random.randint(-10, 10, size=(3,3)) 

In [4]:
matrix_1, matrix_2, matrix_3

(array([[-4,  9,  4],
        [ 0, -3, -4],
        [ 8,  0,  0]]),
 array([[ -7,  -3,  -8],
        [ -9,   1,  -5],
        [ -9, -10,   1]]),
 array([[ 1,  6, -1],
        [ 5,  4,  4],
        [ 8,  1,  9]]))

In [5]:
# computes the inverse of each matrix 
inverse_1 = np.linalg.inv(matrix_1)
inverse_2 = np.linalg.inv(matrix_2)
inverse_3 = np.linalg.inv(matrix_3)

In [6]:
inverse_1, inverse_2, inverse_3

(array([[ 0.        ,  0.        ,  0.125     ],
        [ 0.16666667,  0.16666667,  0.08333333],
        [-0.125     , -0.375     , -0.0625    ]]),
 array([[ 0.0801964 , -0.13584288, -0.03764321],
        [-0.08837971,  0.12929624, -0.06055646],
        [-0.16202946,  0.07037643,  0.05564648]]),
 array([[-1.68421053,  2.89473684, -1.47368421],
        [ 0.68421053, -0.89473684,  0.47368421],
        [ 1.42105263, -2.47368421,  1.36842105]]))

 Compute the product of each matrix with its inverse to check that you obtain the identity matrix.

In [7]:
product_1 = np.dot(matrix_1, inverse_1) 

In [8]:
product_1 

array([[ 1.00000000e+00, -2.22044605e-16,  0.00000000e+00],
       [-1.11022302e-16,  1.00000000e+00, -5.55111512e-17],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [9]:
product_2 = np.dot(matrix_2, inverse_2) 

In [10]:
product_2

array([[ 1.00000000e+00,  0.00000000e+00,  5.55111512e-17],
       [ 2.77555756e-17,  1.00000000e+00,  6.93889390e-18],
       [ 1.94289029e-16, -4.85722573e-16,  1.00000000e+00]])

In [11]:
product_3 = np.dot(matrix_3, inverse_3) 

In [12]:
product_3

array([[1.00000000e+00, 4.44089210e-16, 2.22044605e-16],
       [0.00000000e+00, 1.00000000e+00, 8.88178420e-16],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

These results confirm that the inverses computes using NUMPY are correct. Small values close to 0 appears but thats because of floating point arthamtic. 